import React from 'react';
import { Building2, Tag } from 'lucide-react';

export const QuestionBody = React.memo(function QuestionBody({
  question,
  realCompanies
}) {
  return (
    <>
      {/* AI Challenge Banner */}
      {question.isAiGenerated && (
        <div style={{
          marginBottom: 16, padding: '10px 14px', borderRadius: 8,
          background: 'linear-gradient(135deg, rgba(139,92,246,0.08), rgba(59,130,246,0.08))',
          border: '1px solid rgba(139,92,246,0.2)',
          display: 'flex', alignItems: 'flex-start', gap: 10,
        }}>
          <span style={{ fontSize: 20, flexShrink: 0 }}>🤖</span>
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#8b5cf6', marginBottom: 3 }}>
              AI-Generated {question.companyName ? `${question.companyName} Challenge` : 'Challenge'}
            </div>
            <div style={{ fontSize: 11, color: 'var(--muted)', lineHeight: 1.5 }}>
              This question was generated by AI. It uses real schema tables — try it like any other question!
              No automatic validation — focus on writing correct SQL.
            </div>
          </div>
        </div>
      )}

      {/* Prompt */}
      <div style={{ fontSize: 15, lineHeight: 1.6, color: 'var(--text)', marginBottom: 20, fontWeight: 500 }}>
        {question.prompt}
      </div>

      {/* Keywords */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 24 }}>
        {/* Dynamic Supabase Companies */}
        {realCompanies.length > 0 && (
          <span key={'comp-group'} style={{
            background: 'transparent',
            color: 'var(--text-secondary)',
            fontSize: 12,
            fontWeight: 500,
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            padding: '2px 0',
          }}>
            <Building2 size={13} style={{ color: 'var(--primary)' }} />
            <span><strong style={{color: 'var(--text)', fontWeight: 600}}>Asked in:</strong> {realCompanies.join(', ')}</span>
          </span>
        )}

        {(question.keywords || []).map(kw => {
          // Ignore the local hardcoded fake company tags
          if (kw.startsWith('company:')) {
            return null;
          }
          if (kw.startsWith('topic:')) {
            const topic = kw.split(':')[1];
            return (
              <span key={kw} style={{
                background: 'var(--primary-muted)',
                color: 'var(--primary)',
                border: 'none',
                padding: '4px 12px',
                borderRadius: 99,
                fontSize: 12,
                fontWeight: 600,
                display: 'flex',
                alignItems: 'center',
                gap: 6
              }}>
                <Tag size={13} /> {topic}
              </span>
            );
          }
          return (
            <span key={kw} style={{
              background: 'var(--surface-2)',
              border: '1px solid var(--border)',
              color: 'var(--text-secondary)',
              padding: '4px 10px',
              borderRadius: 6,
              fontSize: 11,
              fontWeight: 600
            }}>
              {kw}
            </span>
          );
        })}
      </div>
    </>
  );
});
