import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const targetFile = path.join(__dirname, '../src/data/questions/airlines.jsx');

const code = `const noRows = {
  columns: [],
  rows: []
};

const make = (id, db, diff, kw, prompt, h1, h2, h3, sql) => ({
  id,
  db,
  difficulty: diff,
  keywords: kw,
  prompt,
  hint1: h1,
  hint2: h2,
  hint3: h3,
  solutionSQL: sql,
  expectedResult: noRows
});

// AIRLINES QUESTIONS (IDs 181-240)
export const airlinesQuestions = [
  // EASY
  make(181, 'airlines', 'easy', ['Select', 'Where', 'company:Delta', 'topic:Basic SQL'], "Find all flights that are currently 'Delayed' along with their flight number, scheduled departure, and origin airport ID.", "WHERE status = 'Delayed'", "WHERE status = 'Delayed'", "SELECT flight_no, scheduled_dep, origin_id FROM flights WHERE status = 'Delayed';", "SELECT flight_no, scheduled_dep, origin_id FROM flights WHERE status = 'Delayed';"),
  make(182, 'airlines', 'easy', ['Select', 'Where', 'company:United', 'topic:Basic SQL'], "Identify the aircraft models in our fleet that have a seating capacity of 300 or more passengers. Return model, manufacturer, and seating_capacity.", "WHERE seating_capacity >= 300", "WHERE seating_capacity >= 300", "SELECT model, manufacturer, seating_capacity FROM aircraft WHERE seating_capacity >= 300;", "SELECT model, manufacturer, seating_capacity FROM aircraft WHERE seating_capacity >= 300;"),
  make(183, 'airlines', 'easy', ['Select', 'Distinct', 'company:Airbnb', 'topic:Basic SQL'], "List the distinct nationalities of our passengers to understand our international customer base. Order alphabetically.", "SELECT DISTINCT", "ORDER BY nationality", "SELECT DISTINCT nationality FROM passengers ORDER BY nationality;", "SELECT DISTINCT nationality FROM passengers ORDER BY nationality;"),
  make(184, 'airlines', 'easy', ['Aggregate', 'company:Snowflake', 'topic:Aggregate Functions'], "Calculate the total number of bookings made for Business class. Return as \\\`business_class_bookings\\\`.", "COUNT(*) with WHERE clause", "WHERE cabin_class = 'Business'", "SELECT COUNT(*) AS business_class_bookings FROM bookings WHERE cabin_class = 'Business';", "SELECT COUNT(*) AS business_class_bookings FROM bookings WHERE cabin_class = 'Business';"),
  make(185, 'airlines', 'easy', ['Where', 'Date Function', 'company:Databricks', 'topic:Basic SQL'], "Show the flight numbers and actual departure times of flights that departed after their scheduled departure time (actual_dep > scheduled_dep).", "Compare actual_dep and scheduled_dep", "WHERE actual_dep > scheduled_dep", "SELECT flight_no, actual_dep FROM flights WHERE actual_dep > scheduled_dep;", "SELECT flight_no, actual_dep FROM flights WHERE actual_dep > scheduled_dep;"),
  make(186, 'airlines', 'easy', ['Where', 'Date Function', 'company:Uber', 'topic:Basic SQL'], "Retrieve the names (first and last), passport number, and date of birth of all passengers born before 1980.", "WHERE dob < '1980-01-01'", "WHERE dob < '1980-01-01'", "SELECT first_name, last_name, passport_no, dob FROM passengers WHERE dob < '1980-01-01';", "SELECT first_name, last_name, passport_no, dob FROM passengers WHERE dob < '1980-01-01';"),
  make(187, 'airlines', 'easy', ['Order By', 'Limit', 'company:Amazon', 'topic:Basic SQL'], "Find the top 5 most expensive booking prices ever recorded. Return just the price, ordered descending.", "ORDER BY price DESC LIMIT 5", "ORDER BY price DESC LIMIT 5", "SELECT price FROM bookings ORDER BY price DESC LIMIT 5;", "SELECT price FROM bookings ORDER BY price DESC LIMIT 5;"),
  make(188, 'airlines', 'easy', ['Aggregate', 'Where', 'company:Meta', 'topic:Aggregate Functions'], "Find the average duration in minutes (avg_duration_mins) of all routes originating from JFK (origin_id = 1). Return as avg_duration.", "AVG(avg_duration_mins)", "WHERE origin_id = 1", "SELECT AVG(avg_duration_mins) AS avg_duration FROM routes WHERE origin_id = 1;", "SELECT ROUND(AVG(avg_duration_mins), 2) AS avg_duration FROM routes WHERE origin_id = 1;"),
  make(189, 'airlines', 'easy', ['Group By', 'Aggregate', 'company:Netflix', 'topic:Aggregate Functions'], "Count the number of active employees we have by their role. Return role and employee_count.", "GROUP BY role", "COUNT(employee_id)", "SELECT role, COUNT(employee_id) AS employee_count FROM employees GROUP BY role;", "SELECT role, COUNT(employee_id) AS employee_count FROM employees GROUP BY role;"),
  make(190, 'airlines', 'easy', ['Where', 'Null Handling', 'company:Apple', 'topic:Basic SQL'], "Retrieve the flight IDs of flights that have not yet had a seat assigned for passenger_id 15 (where seat_no IS NULL).", "WHERE seat_no IS NULL", "AND passenger_id = 15", "SELECT flight_id FROM bookings WHERE passenger_id = 15 AND seat_no IS NULL;", "SELECT flight_id FROM bookings WHERE passenger_id = 15 AND seat_no IS NULL;"),
  make(191, 'airlines', 'easy', ['Where', 'In', 'company:Microsoft', 'topic:Basic SQL'], "Identify all airports located in the 'USA' or 'Canada'. Return name, city, and country.", "WHERE country IN ('USA', 'Canada')", "WHERE country IN ('USA', 'Canada')", "SELECT name, city, country FROM airports WHERE country IN ('USA', 'Canada');", "SELECT name, city, country FROM airports WHERE country IN ('USA', 'Canada');"),
  make(192, 'airlines', 'easy', ['Aggregate', 'Where', 'company:Stripe', 'topic:Aggregate Functions'], "Calculate the average price of an 'Economy' class ticket across all bookings. Return as \\\`avg_economy_price\\\`.", "AVG(price)", "WHERE cabin_class = 'Economy'", "SELECT AVG(price) AS avg_economy_price FROM bookings WHERE cabin_class = 'Economy';", "SELECT ROUND(AVG(price), 2) AS avg_economy_price FROM bookings WHERE cabin_class = 'Economy';"),
  make(193, 'airlines', 'easy', ['Aggregate', 'Distinct', 'company:Oracle', 'topic:Aggregate Functions'], "Determine how many unique aircraft manufacturers make up our fleet. Return as \\\`manufacturer_count\\\`.", "COUNT(DISTINCT manufacturer)", "COUNT(DISTINCT manufacturer)", "SELECT COUNT(DISTINCT manufacturer) AS manufacturer_count FROM aircraft;", "SELECT COUNT(DISTINCT manufacturer) AS manufacturer_count FROM aircraft;"),
  make(194, 'airlines', 'easy', ['Where', 'Order By', 'company:Salesforce', 'topic:Basic SQL'], "Find all routes (origin_id, destination_id) that cover a distance of over 8000 km, ordered by distance_km descending.", "WHERE distance_km > 8000", "ORDER BY distance_km DESC", "SELECT origin_id, destination_id, distance_km FROM routes WHERE distance_km > 8000 ORDER BY distance_km DESC;", "SELECT origin_id, destination_id, distance_km FROM routes WHERE distance_km > 8000 ORDER BY distance_km DESC;"),
  make(195, 'airlines', 'easy', ['Where', 'Like', 'company:Adobe', 'topic:Basic SQL'], "Extract the flight_no, scheduled_dep, and status for all flights scheduled to depart on '2024-02-14'.", "Use LIKE or DATE() function", "WHERE DATE(scheduled_dep) = '2024-02-14'", "SELECT flight_no, scheduled_dep, status FROM flights WHERE DATE(scheduled_dep) = '2024-02-14';", "SELECT flight_no, scheduled_dep, status FROM flights WHERE DATE(scheduled_dep) = '2024-02-14';"),
  make(196, 'airlines', 'easy', ['Aggregate', 'Where', 'company:Amazon', 'topic:Aggregate Functions'], "Calculate the total seating capacity available across all Airbus aircraft in the fleet. Return as \\\`total_airbus_capacity\\\`.", "SUM(seating_capacity)", "WHERE manufacturer = 'Airbus'", "SELECT SUM(seating_capacity) AS total_airbus_capacity FROM aircraft WHERE manufacturer = 'Airbus';", "SELECT SUM(seating_capacity) AS total_airbus_capacity FROM aircraft WHERE manufacturer = 'Airbus';"),
  make(197, 'airlines', 'easy', ['Aggregate', 'Where', 'company:Snowflake', 'topic:Aggregate Functions'], "Find the minimum, maximum, and average price paid for bookings on flight_id 1.", "MIN(price), MAX(price), AVG(price)", "WHERE flight_id = 1", "SELECT MIN(price), MAX(price), AVG(price) FROM bookings WHERE flight_id = 1;", "SELECT ROUND(MIN(price), 2) AS min_price, ROUND(MAX(price), 2) AS max_price, ROUND(AVG(price), 2) AS avg_price FROM bookings WHERE flight_id = 1;"),
  make(198, 'airlines', 'easy', ['Order By', 'Limit', 'company:Databricks', 'topic:Basic SQL'], "List the 3 most recently manufactured aircraft in the fleet. Return model and year_manufactured.", "ORDER BY year_manufactured DESC", "LIMIT 3", "SELECT model, year_manufactured FROM aircraft ORDER BY year_manufactured DESC LIMIT 3;", "SELECT model, year_manufactured FROM aircraft ORDER BY year_manufactured DESC LIMIT 3;"),
  make(199, 'airlines', 'easy', ['Where', 'Null Handling', 'company:Uber', 'topic:Basic SQL'], "Find all bookings where the passenger checked in (checked_in = 1) but the seat_no is NULL. Return booking_id and passenger_id.", "WHERE checked_in = 1 AND seat_no IS NULL", "WHERE checked_in = 1 AND seat_no IS NULL", "SELECT booking_id, passenger_id FROM bookings WHERE checked_in = 1 AND seat_no IS NULL;", "SELECT booking_id, passenger_id FROM bookings WHERE checked_in = 1 AND seat_no IS NULL;"),
  make(200, 'airlines', 'easy', ['Aggregate', 'Where', 'company:Airbnb', 'topic:Aggregate Functions'], "Retrieve the total number of flights that were 'Cancelled'. Return as \\\`cancelled_flights\\\`.", "COUNT(*)", "WHERE status = 'Cancelled'", "SELECT COUNT(*) AS cancelled_flights FROM flights WHERE status = 'Cancelled';", "SELECT COUNT(*) AS cancelled_flights FROM flights WHERE status = 'Cancelled';"),

  // MEDIUM
  make(201, 'airlines', 'medium', ['Join', 'company:Delta', 'topic:Joins'], "Find the full name (first_name + ' ' + last_name) of the passengers who booked a 'First' class ticket and the price they paid.", "JOIN passengers and bookings", "WHERE cabin_class = 'First'", "SELECT p.first_name || ' ' || p.last_name AS full_name, b.price FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id WHERE b.cabin_class = 'First';", "SELECT p.first_name || ' ' || p.last_name AS full_name, b.price FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id WHERE b.cabin_class = 'First';"),
  make(202, 'airlines', 'medium', ['Group By', 'Aggregate', 'company:United', 'topic:Aggregate Functions'], "Calculate the total revenue generated from each cabin class. Return cabin_class and total_revenue, ordered by total_revenue desc.", "GROUP BY cabin_class", "SUM(price)", "SELECT cabin_class, SUM(price) AS total_revenue FROM bookings GROUP BY cabin_class ORDER BY total_revenue DESC;", "SELECT cabin_class, SUM(price) AS total_revenue FROM bookings GROUP BY cabin_class ORDER BY total_revenue DESC;"),
  make(203, 'airlines', 'medium', ['Join', 'company:Airbnb', 'topic:Joins'], "List the flight numbers, scheduled departure, and the name of the destination airport for all flights departing from 'LHR' (origin).", "JOIN flights and airports twice or filter carefully", "JOIN airports a_orig ON f.origin_id = a_orig.airport_id", "SELECT f.flight_no, f.scheduled_dep, a_dest.name AS destination_airport FROM flights f JOIN airports a_orig ON f.origin_id = a_orig.airport_id JOIN airports a_dest ON f.destination_id = a_dest.airport_id WHERE a_orig.iata_code = 'LHR';", "SELECT f.flight_no, f.scheduled_dep, a_dest.name AS destination_airport FROM flights f JOIN airports a_orig ON f.origin_id = a_orig.airport_id JOIN airports a_dest ON f.destination_id = a_dest.airport_id WHERE a_orig.iata_code = 'LHR';"),
  make(204, 'airlines', 'medium', ['Join', 'Aggregate', 'company:Amazon', 'topic:Joins'], "Determine the average distance of routes flown by passengers of 'British' nationality. Return avg_distance_km.", "JOIN passengers -> bookings -> flights -> routes", "AVG(distance_km) WHERE nationality = 'British'", "SELECT AVG(r.distance_km) AS avg_distance_km FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id JOIN flights f ON b.flight_id = f.flight_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id WHERE p.nationality = 'British';", "SELECT ROUND(AVG(r.distance_km), 2) AS avg_distance_km FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id JOIN flights f ON b.flight_id = f.flight_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id WHERE p.nationality = 'British';"),
  make(205, 'airlines', 'medium', ['Join', 'Aggregate', 'company:Snowflake', 'topic:Joins'], "Find the total number of bookings made on aircraft manufactured by 'Boeing'. Return as boeing_bookings.", "JOIN bookings -> flights -> aircraft", "COUNT(*) WHERE manufacturer = 'Boeing'", "SELECT COUNT(b.booking_id) AS boeing_bookings FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN aircraft a ON f.aircraft_id = a.aircraft_id WHERE a.manufacturer = 'Boeing';", "SELECT COUNT(b.booking_id) AS boeing_bookings FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN aircraft a ON f.aircraft_id = a.aircraft_id WHERE a.manufacturer = 'Boeing';"),
  make(206, 'airlines', 'medium', ['Left Join', 'Null Handling', 'company:Meta', 'topic:Joins'], "Identify any airports that have no flights originating from them in the dataset. Return airport name and city.", "LEFT JOIN flights on airport_id = origin_id", "WHERE flight_id IS NULL", "SELECT a.name, a.city FROM airports a LEFT JOIN flights f ON a.airport_id = f.origin_id WHERE f.flight_id IS NULL;", "SELECT a.name, a.city FROM airports a LEFT JOIN flights f ON a.airport_id = f.origin_id WHERE f.flight_id IS NULL;"),
  make(207, 'airlines', 'medium', ['Join', 'Aggregate', 'Math', 'company:Netflix', 'topic:Joins'], "Calculate the passenger load factor (total bookings / seating capacity * 100) for flight_id 5. Return as load_factor_pct.", "COUNT(bookings) / seating_capacity * 100.0", "JOIN flights and aircraft", "SELECT COUNT(b.booking_id) * 100.0 / a.seating_capacity AS load_factor_pct FROM flights f JOIN aircraft a ON f.aircraft_id = a.aircraft_id LEFT JOIN bookings b ON f.flight_id = b.flight_id WHERE f.flight_id = 5 GROUP BY a.seating_capacity;", "SELECT ROUND(COUNT(b.booking_id) * 100.0 / a.seating_capacity, 2) AS load_factor_pct FROM flights f JOIN aircraft a ON f.aircraft_id = a.aircraft_id LEFT JOIN bookings b ON f.flight_id = b.flight_id WHERE f.flight_id = 5 GROUP BY a.seating_capacity;"),
  make(208, 'airlines', 'medium', ['Group By', 'Order By', 'company:Apple', 'topic:Aggregate Functions'], "Find the passenger(s) who have spent the most on bookings overall. Return first_name, last_name, and total_spent.", "JOIN passengers and bookings, GROUP BY passenger", "SUM(price) ORDER BY total_spent DESC LIMIT 1", "SELECT p.first_name, p.last_name, SUM(b.price) AS total_spent FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id GROUP BY p.passenger_id ORDER BY total_spent DESC LIMIT 1;", "SELECT p.first_name, p.last_name, SUM(b.price) AS total_spent FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id GROUP BY p.passenger_id ORDER BY total_spent DESC LIMIT 1;"),
  make(209, 'airlines', 'medium', ['Join', 'Where', 'company:Uber', 'topic:Joins'], "List the names (first and last) of all employees who have worked as a 'Flight Attendant' on a flight that was 'Delayed'.", "JOIN employees -> crew -> flights", "WHERE role = 'Flight Attendant' AND status = 'Delayed'", "SELECT DISTINCT e.first_name, e.last_name FROM employees e JOIN crew c ON e.employee_id = c.employee_id JOIN flights f ON c.flight_id = f.flight_id WHERE c.role = 'Flight Attendant' AND f.status = 'Delayed';", "SELECT DISTINCT e.first_name, e.last_name FROM employees e JOIN crew c ON e.employee_id = c.employee_id JOIN flights f ON c.flight_id = f.flight_id WHERE c.role = 'Flight Attendant' AND f.status = 'Delayed';"),
  make(210, 'airlines', 'medium', ['Date Function', 'Aggregate', 'company:Databricks', 'topic:Aggregate Functions'], "Calculate the average delay in minutes for flights arriving at 'CDG' (actual_arr - scheduled_arr). Return as avg_delay_mins.", "Use julianday to get difference", "(julianday(actual_arr) - julianday(scheduled_arr)) * 1440", "SELECT AVG((julianday(f.actual_arr) - julianday(f.scheduled_arr)) * 1440) AS avg_delay_mins FROM flights f JOIN airports a ON f.destination_id = a.airport_id WHERE a.iata_code = 'CDG' AND f.actual_arr IS NOT NULL;", "SELECT ROUND(AVG((julianday(f.actual_arr) - julianday(f.scheduled_arr)) * 1440), 2) AS avg_delay_mins FROM flights f JOIN airports a ON f.destination_id = a.airport_id WHERE a.iata_code = 'CDG' AND f.actual_arr IS NOT NULL;"),
  make(211, 'airlines', 'medium', ['Join', 'Group By', 'company:Oracle', 'topic:Aggregate Functions'], "Which aircraft model has flown the most flights? Return model and flight_count.", "JOIN aircraft and flights, GROUP BY model", "ORDER BY flight_count DESC LIMIT 1", "SELECT a.model, COUNT(f.flight_id) AS flight_count FROM aircraft a JOIN flights f ON a.aircraft_id = f.aircraft_id GROUP BY a.model ORDER BY flight_count DESC LIMIT 1;", "SELECT a.model, COUNT(f.flight_id) AS flight_count FROM aircraft a JOIN flights f ON a.aircraft_id = f.aircraft_id GROUP BY a.model ORDER BY flight_count DESC LIMIT 1;"),
  make(212, 'airlines', 'medium', ['Join', 'company:Stripe', 'topic:Joins'], "For each route, show the origin city and destination city names. Return origin_city, destination_city, and distance_km.", "JOIN routes to airports twice", "ON r.origin_id = a1.airport_id AND r.destination_id = a2.airport_id", "SELECT a1.city AS origin_city, a2.city AS destination_city, r.distance_km FROM routes r JOIN airports a1 ON r.origin_id = a1.airport_id JOIN airports a2 ON r.destination_id = a2.airport_id;", "SELECT a1.city AS origin_city, a2.city AS destination_city, r.distance_km FROM routes r JOIN airports a1 ON r.origin_id = a1.airport_id JOIN airports a2 ON r.destination_id = a2.airport_id;"),
  make(213, 'airlines', 'medium', ['Subquery', 'Group By', 'company:Salesforce', 'topic:Subqueries'], "Find the flight numbers of flights whose average booking price is higher than the overall average booking price of all flights.", "HAVING AVG(price) > (SELECT AVG(price) FROM bookings)", "GROUP BY flight_no", "SELECT f.flight_no FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no HAVING AVG(b.price) > (SELECT AVG(price) FROM bookings);", "SELECT f.flight_no FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no HAVING AVG(b.price) > (SELECT AVG(price) FROM bookings);"),
  make(214, 'airlines', 'medium', ['Join', 'Group By', 'company:Adobe', 'topic:Aggregate Functions'], "What is the most popular destination city based on the number of bookings? Return destination_city and total_bookings.", "JOIN bookings -> flights -> airports(destination)", "GROUP BY city ORDER BY total_bookings DESC LIMIT 1", "SELECT a.city AS destination_city, COUNT(b.booking_id) AS total_bookings FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN airports a ON f.destination_id = a.airport_id GROUP BY a.city ORDER BY total_bookings DESC LIMIT 1;", "SELECT a.city AS destination_city, COUNT(b.booking_id) AS total_bookings FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN airports a ON f.destination_id = a.airport_id GROUP BY a.city ORDER BY total_bookings DESC LIMIT 1;"),
  make(215, 'airlines', 'medium', ['Case', 'Aggregate', 'company:Amazon', 'topic:Basic SQL'], "Categorize routes into 'Short-haul' (<1500km), 'Medium-haul' (1500-4000km), and 'Long-haul' (>4000km). Count the number of routes in each category. Return category and route_count.", "CASE WHEN distance_km < 1500 THEN ... END", "GROUP BY category", "SELECT CASE WHEN distance_km < 1500 THEN 'Short-haul' WHEN distance_km <= 4000 THEN 'Medium-haul' ELSE 'Long-haul' END AS category, COUNT(*) AS route_count FROM routes GROUP BY category;", "SELECT CASE WHEN distance_km < 1500 THEN 'Short-haul' WHEN distance_km <= 4000 THEN 'Medium-haul' ELSE 'Long-haul' END AS category, COUNT(*) AS route_count FROM routes GROUP BY category;"),
  make(216, 'airlines', 'medium', ['Join', 'Distinct', 'company:Microsoft', 'topic:Joins'], "Find the total number of distinct passengers who flew on a flight piloted by employee 'John Doe' (Pilot or Co-Pilot).", "JOIN passengers -> bookings -> flights -> crew -> employees", "WHERE first_name='John' AND last_name='Doe'", "SELECT COUNT(DISTINCT b.passenger_id) AS total_passengers FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN crew c ON f.flight_id = c.flight_id JOIN employees e ON c.employee_id = e.employee_id WHERE e.first_name = 'John' AND e.last_name = 'Doe';", "SELECT COUNT(DISTINCT b.passenger_id) AS total_passengers FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN crew c ON f.flight_id = c.flight_id JOIN employees e ON c.employee_id = e.employee_id WHERE e.first_name = 'John' AND e.last_name = 'Doe';"),
  make(217, 'airlines', 'medium', ['Date Function', 'Group By', 'company:Snowflake', 'topic:Aggregate Functions'], "Show the daily revenue trend for January 2024 (using scheduled_dep). Return the date (YYYY-MM-DD) and total_revenue.", "GROUP BY DATE(scheduled_dep)", "WHERE scheduled_dep LIKE '2024-01%'", "SELECT DATE(f.scheduled_dep) AS flight_date, SUM(b.price) AS total_revenue FROM flights f JOIN bookings b ON f.flight_id = b.flight_id WHERE strftime('%Y-%m', f.scheduled_dep) = '2024-01' GROUP BY DATE(f.scheduled_dep) ORDER BY flight_date;", "SELECT DATE(f.scheduled_dep) AS flight_date, SUM(b.price) AS total_revenue FROM flights f JOIN bookings b ON f.flight_id = b.flight_id WHERE strftime('%Y-%m', f.scheduled_dep) = '2024-01' GROUP BY DATE(f.scheduled_dep) ORDER BY flight_date;"),
  make(218, 'airlines', 'medium', ['Self Join', 'company:Uber', 'topic:Joins'], "Find pairs of airports in the same country. Return country, airport1_iata, airport2_iata (where airport1_iata < airport2_iata).", "JOIN airports a1 ON a1.country = a2.country", "AND a1.iata_code < a2.iata_code", "SELECT a1.country, a1.iata_code AS airport1_iata, a2.iata_code AS airport2_iata FROM airports a1 JOIN airports a2 ON a1.country = a2.country AND a1.iata_code < a2.iata_code;", "SELECT a1.country, a1.iata_code AS airport1_iata, a2.iata_code AS airport2_iata FROM airports a1 JOIN airports a2 ON a1.country = a2.country AND a1.iata_code < a2.iata_code;"),
  make(219, 'airlines', 'medium', ['Group By', 'Math', 'company:Databricks', 'topic:Aggregate Functions'], "Calculate the cancellation rate (cancelled flights / total flights * 100) for each airline manufacturer. Return manufacturer and cancellation_rate.", "SUM(CASE WHEN status='Cancelled' THEN 1 ELSE 0 END) / COUNT(*)", "JOIN flights and aircraft", "SELECT a.manufacturer, ROUND(SUM(CASE WHEN f.status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS cancellation_rate FROM aircraft a JOIN flights f ON a.aircraft_id = f.aircraft_id GROUP BY a.manufacturer;", "SELECT a.manufacturer, ROUND(SUM(CASE WHEN f.status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS cancellation_rate FROM aircraft a JOIN flights f ON a.aircraft_id = f.aircraft_id GROUP BY a.manufacturer;"),
  make(220, 'airlines', 'medium', ['Subquery', 'company:Meta', 'topic:Subqueries'], "Identify the passenger who booked the earliest ticket (lowest booked_at). Return their first_name, last_name, and the booked_at timestamp.", "ORDER BY booked_at ASC LIMIT 1", "JOIN passengers and bookings", "SELECT p.first_name, p.last_name, b.booked_at FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id ORDER BY b.booked_at ASC LIMIT 1;", "SELECT p.first_name, p.last_name, b.booked_at FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id ORDER BY b.booked_at ASC LIMIT 1;"),
  make(221, 'airlines', 'medium', ['Join', 'Group By', 'company:Airbnb', 'topic:Joins'], "Find the route (origin IATA and destination IATA) that generates the highest average revenue per passenger.", "JOIN bookings, flights, airports", "GROUP BY route, ORDER BY avg_revenue DESC", "SELECT a1.iata_code AS origin, a2.iata_code AS destination, ROUND(AVG(b.price), 2) AS avg_revenue FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN airports a1 ON f.origin_id = a1.airport_id JOIN airports a2 ON f.destination_id = a2.airport_id GROUP BY a1.iata_code, a2.iata_code ORDER BY avg_revenue DESC LIMIT 1;", "SELECT a1.iata_code AS origin, a2.iata_code AS destination, ROUND(AVG(b.price), 2) AS avg_revenue FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN airports a1 ON f.origin_id = a1.airport_id JOIN airports a2 ON f.destination_id = a2.airport_id GROUP BY a1.iata_code, a2.iata_code ORDER BY avg_revenue DESC LIMIT 1;"),
  make(222, 'airlines', 'medium', ['Group By', 'Having', 'company:Oracle', 'topic:Aggregate Functions'], "List all flights where the number of checked-in passengers is less than 50% of the total bookings for that flight. Return flight_no.", "HAVING SUM(checked_in) < COUNT(*) * 0.5", "GROUP BY flight_no", "SELECT f.flight_no FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no HAVING SUM(b.checked_in) < COUNT(b.booking_id) * 0.5;", "SELECT f.flight_no FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no HAVING SUM(b.checked_in) < COUNT(b.booking_id) * 0.5;"),
  make(223, 'airlines', 'medium', ['Join', 'Aggregate', 'company:Apple', 'topic:Joins'], "Find the total distance flown (sum of route distances) by aircraft 'Boeing 737-800' (model) across all its completed flights ('Arrived').", "JOIN aircraft -> flights -> routes", "WHERE model = 'Boeing 737-800' AND status = 'Arrived'", "SELECT SUM(r.distance_km) AS total_distance FROM aircraft a JOIN flights f ON a.aircraft_id = f.aircraft_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id WHERE a.model = 'Boeing 737-800' AND f.status = 'Arrived';", "SELECT SUM(r.distance_km) AS total_distance FROM aircraft a JOIN flights f ON a.aircraft_id = f.aircraft_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id WHERE a.model = 'Boeing 737-800' AND f.status = 'Arrived';"),
  make(224, 'airlines', 'medium', ['Date Function', 'Group By', 'company:Netflix', 'topic:Aggregate Functions'], "Which day of the week has the highest average flight delay (actual_arr - scheduled_arr)? Return the day of week (0=Sun, 6=Sat) and average delay.", "strftime('%w', scheduled_dep)", "ORDER BY avg_delay DESC LIMIT 1", "SELECT strftime('%w', scheduled_dep) AS dow, ROUND(AVG((julianday(actual_arr) - julianday(scheduled_arr))*1440), 2) AS avg_delay FROM flights WHERE actual_arr IS NOT NULL GROUP BY dow ORDER BY avg_delay DESC LIMIT 1;", "SELECT strftime('%w', scheduled_dep) AS dow, ROUND(AVG((julianday(actual_arr) - julianday(scheduled_arr))*1440), 2) AS avg_delay FROM flights WHERE actual_arr IS NOT NULL GROUP BY dow ORDER BY avg_delay DESC LIMIT 1;"),
  make(225, 'airlines', 'medium', ['Group By', 'Having', 'company:Stripe', 'topic:Subqueries'], "List the names of passengers who have traveled in all three cabin classes ('Economy', 'Business', 'First') at least once.", "GROUP BY passenger, HAVING COUNT(DISTINCT cabin_class) = 3", "WHERE cabin_class IN ('Economy', 'Business', 'First')", "SELECT p.first_name, p.last_name FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id WHERE b.cabin_class IN ('Economy', 'Business', 'First') GROUP BY p.passenger_id HAVING COUNT(DISTINCT b.cabin_class) = 3;", "SELECT p.first_name, p.last_name FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id WHERE b.cabin_class IN ('Economy', 'Business', 'First') GROUP BY p.passenger_id HAVING COUNT(DISTINCT b.cabin_class) = 3;"),

  // HARD
  make(226, 'airlines', 'hard', ['Window Function', 'company:Salesforce', 'topic:Window Functions'], "Rank the destination airports by total arriving passenger volume using DENSE_RANK(). Return airport name, total_passengers, and rank.", "DENSE_RANK() OVER (ORDER BY total_passengers DESC)", "Join bookings, flights, airports", "SELECT a.name, COUNT(b.booking_id) AS total_passengers, DENSE_RANK() OVER (ORDER BY COUNT(b.booking_id) DESC) AS rank FROM airports a JOIN flights f ON a.airport_id = f.destination_id JOIN bookings b ON f.flight_id = b.flight_id GROUP BY a.name;", "SELECT a.name, COUNT(b.booking_id) AS total_passengers, DENSE_RANK() OVER (ORDER BY COUNT(b.booking_id) DESC) AS rank FROM airports a JOIN flights f ON a.airport_id = f.destination_id JOIN bookings b ON f.flight_id = b.flight_id GROUP BY a.name;"),
  make(227, 'airlines', 'hard', ['Window Function', 'CTE', 'company:Databricks', 'topic:Window Functions'], "Calculate the running total of revenue for flight_id 10 ordered by booking time. Return booking_id, booked_at, price, and running_revenue.", "SUM(price) OVER (ORDER BY booked_at)", "WHERE flight_id = 10", "SELECT booking_id, booked_at, price, SUM(price) OVER (ORDER BY booked_at) AS running_revenue FROM bookings WHERE flight_id = 10;", "SELECT booking_id, booked_at, price, SUM(price) OVER (ORDER BY booked_at) AS running_revenue FROM bookings WHERE flight_id = 10;"),
  make(228, 'airlines', 'hard', ['Window Function', 'Lead/Lag', 'company:Amazon', 'topic:Window Functions'], "Determine the time difference in minutes between each consecutive booking made by passenger_id 1. Return booking_id, booked_at, and mins_since_last_booking.", "LAG(booked_at) OVER (ORDER BY booked_at)", "julianday(booked_at) - julianday(lagged)", "SELECT booking_id, booked_at, ROUND((julianday(booked_at) - julianday(LAG(booked_at) OVER (ORDER BY booked_at))) * 1440) AS mins_since_last_booking FROM bookings WHERE passenger_id = 1;", "SELECT booking_id, booked_at, ROUND((julianday(booked_at) - julianday(LAG(booked_at) OVER (ORDER BY booked_at))) * 1440) AS mins_since_last_booking FROM bookings WHERE passenger_id = 1;"),
  make(229, 'airlines', 'hard', ['Window Function', 'company:Uber', 'topic:Window Functions'], "Identify the most popular route (by total bookings) for each passenger nationality. Return nationality, origin_id, destination_id, and total_bookings.", "Use ROW_NUMBER() OVER (PARTITION BY nationality ORDER BY total_bookings DESC)", "CTE to group by nationality and route first", "WITH RouteCounts AS (SELECT p.nationality, f.origin_id, f.destination_id, COUNT(b.booking_id) AS total_bookings FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id JOIN flights f ON b.flight_id = f.flight_id GROUP BY p.nationality, f.origin_id, f.destination_id), RankedRoutes AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY nationality ORDER BY total_bookings DESC) AS rn FROM RouteCounts) SELECT nationality, origin_id, destination_id, total_bookings FROM RankedRoutes WHERE rn = 1;", "WITH RouteCounts AS (SELECT p.nationality, f.origin_id, f.destination_id, COUNT(b.booking_id) AS total_bookings FROM passengers p JOIN bookings b ON p.passenger_id = b.passenger_id JOIN flights f ON b.flight_id = f.flight_id GROUP BY p.nationality, f.origin_id, f.destination_id), RankedRoutes AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY nationality ORDER BY total_bookings DESC) AS rn FROM RouteCounts) SELECT nationality, origin_id, destination_id, total_bookings FROM RankedRoutes WHERE rn = 1;"),
  make(230, 'airlines', 'hard', ['Window Function', 'CTE', 'company:Snowflake', 'topic:Window Functions'], "Calculate the Month-over-Month percentage growth in total revenue. Return month (YYYY-MM), revenue, and mom_growth_pct.", "LAG() to get previous month's revenue", "(revenue - prev_revenue) / prev_revenue * 100", "WITH MonthlyRevenue AS (SELECT strftime('%Y-%m', booked_at) AS month, SUM(price) AS revenue FROM bookings GROUP BY month) SELECT month, revenue, ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) / LAG(revenue) OVER (ORDER BY month) * 100, 2) AS mom_growth_pct FROM MonthlyRevenue;", "WITH MonthlyRevenue AS (SELECT strftime('%Y-%m', booked_at) AS month, SUM(price) AS revenue FROM bookings GROUP BY month) SELECT month, revenue, ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) / LAG(revenue) OVER (ORDER BY month) * 100, 2) AS mom_growth_pct FROM MonthlyRevenue;"),
  make(231, 'airlines', 'hard', ['Window Function', 'company:Meta', 'topic:Window Functions'], "Find the 'top spender' passenger for each flight. Return flight_no, passenger_name (first + last), and total_spent.", "ROW_NUMBER() OVER (PARTITION BY flight_no ORDER BY total_spent DESC)", "Group by flight and passenger first", "WITH Spenders AS (SELECT f.flight_no, p.first_name || ' ' || p.last_name AS passenger_name, SUM(b.price) AS total_spent, ROW_NUMBER() OVER (PARTITION BY f.flight_no ORDER BY SUM(b.price) DESC) AS rn FROM flights f JOIN bookings b ON f.flight_id = b.flight_id JOIN passengers p ON b.passenger_id = p.passenger_id GROUP BY f.flight_no, p.passenger_id) SELECT flight_no, passenger_name, total_spent FROM Spenders WHERE rn = 1;", "WITH Spenders AS (SELECT f.flight_no, p.first_name || ' ' || p.last_name AS passenger_name, SUM(b.price) AS total_spent, ROW_NUMBER() OVER (PARTITION BY f.flight_no ORDER BY SUM(b.price) DESC) AS rn FROM flights f JOIN bookings b ON f.flight_id = b.flight_id JOIN passengers p ON b.passenger_id = p.passenger_id GROUP BY f.flight_no, p.passenger_id) SELECT flight_no, passenger_name, total_spent FROM Spenders WHERE rn = 1;"),
  make(232, 'airlines', 'hard', ['Window Function', 'CTE', 'company:Apple', 'topic:Window Functions'], "Calculate the 3-day rolling average of daily total revenue based on booking date. Return date (YYYY-MM-DD) and rolling_avg_revenue.", "ROWS BETWEEN 2 PRECEDING AND CURRENT ROW", "SUM(price) GROUP BY DATE(booked_at) first", "WITH DailyRevenue AS (SELECT DATE(booked_at) AS booking_date, SUM(price) AS daily_revenue FROM bookings GROUP BY booking_date) SELECT booking_date, ROUND(AVG(daily_revenue) OVER (ORDER BY booking_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS rolling_avg_revenue FROM DailyRevenue;", "WITH DailyRevenue AS (SELECT DATE(booked_at) AS booking_date, SUM(price) AS daily_revenue FROM bookings GROUP BY booking_date) SELECT booking_date, ROUND(AVG(daily_revenue) OVER (ORDER BY booking_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS rolling_avg_revenue FROM DailyRevenue;"),
  make(233, 'airlines', 'hard', ['Window Function', 'company:Netflix', 'topic:Window Functions'], "Divide the flights into quartiles based on their total revenue using NTILE(4). Return flight_no, revenue, and revenue_quartile.", "NTILE(4) OVER (ORDER BY revenue DESC)", "Group by flight_no, SUM(price)", "WITH FlightRevenue AS (SELECT f.flight_no, SUM(b.price) AS revenue FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no) SELECT flight_no, revenue, NTILE(4) OVER (ORDER BY revenue DESC) AS revenue_quartile FROM FlightRevenue;", "WITH FlightRevenue AS (SELECT f.flight_no, SUM(b.price) AS revenue FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no) SELECT flight_no, revenue, NTILE(4) OVER (ORDER BY revenue DESC) AS revenue_quartile FROM FlightRevenue;"),
  make(234, 'airlines', 'hard', ['CTE', 'Window Function', 'company:Stripe', 'topic:CTEs'], "Find 'Frequent Flyers': passengers who have flown more than the 90th percentile of total distance flown by all passengers. Return passenger_id and total_distance.", "Calculate total distance per passenger. Use NTILE(10) or percent_rank.", "Or PERCENT_RANK() OVER (ORDER BY total_distance)", "WITH PaxDistance AS (SELECT b.passenger_id, SUM(r.distance_km) AS total_distance FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id GROUP BY b.passenger_id), Percentiles AS (SELECT passenger_id, total_distance, PERCENT_RANK() OVER (ORDER BY total_distance) AS pct_rank FROM PaxDistance) SELECT passenger_id, total_distance FROM Percentiles WHERE pct_rank > 0.9;", "WITH PaxDistance AS (SELECT b.passenger_id, SUM(r.distance_km) AS total_distance FROM bookings b JOIN flights f ON b.flight_id = f.flight_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id GROUP BY b.passenger_id), Percentiles AS (SELECT passenger_id, total_distance, PERCENT_RANK() OVER (ORDER BY total_distance) AS pct_rank FROM PaxDistance) SELECT passenger_id, total_distance FROM Percentiles WHERE pct_rank > 0.9;"),
  make(235, 'airlines', 'hard', ['Window Function', 'company:Adobe', 'topic:Window Functions'], "Calculate the percentage contribution of each cabin class to a flight's total revenue. Return flight_no, cabin_class, class_revenue, and pct_of_flight_revenue.", "SUM(revenue) OVER (PARTITION BY flight_no)", "class_revenue / total_flight_revenue * 100", "WITH ClassRevenue AS (SELECT f.flight_no, b.cabin_class, SUM(b.price) AS class_revenue FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no, b.cabin_class) SELECT flight_no, cabin_class, class_revenue, ROUND(class_revenue * 100.0 / SUM(class_revenue) OVER (PARTITION BY flight_no), 2) AS pct_of_flight_revenue FROM ClassRevenue;", "WITH ClassRevenue AS (SELECT f.flight_no, b.cabin_class, SUM(b.price) AS class_revenue FROM flights f JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_no, b.cabin_class) SELECT flight_no, cabin_class, class_revenue, ROUND(class_revenue * 100.0 / SUM(class_revenue) OVER (PARTITION BY flight_no), 2) AS pct_of_flight_revenue FROM ClassRevenue;"),
  make(236, 'airlines', 'hard', ['Window Function', 'company:Oracle', 'topic:Window Functions'], "For each route (origin_id to destination_id), find the flight with the longest delay (actual_arr - scheduled_arr). Return origin_id, destination_id, flight_no, and delay_mins.", "ROW_NUMBER() OVER (PARTITION BY origin_id, destination_id ORDER BY delay DESC)", "delay_mins = (julianday(actual_arr) - julianday(scheduled_arr)) * 1440", "WITH Delays AS (SELECT origin_id, destination_id, flight_no, ROUND((julianday(actual_arr) - julianday(scheduled_arr))*1440, 2) AS delay_mins, ROW_NUMBER() OVER (PARTITION BY origin_id, destination_id ORDER BY (julianday(actual_arr) - julianday(scheduled_arr)) DESC) AS rn FROM flights WHERE actual_arr IS NOT NULL) SELECT origin_id, destination_id, flight_no, delay_mins FROM Delays WHERE rn = 1;", "WITH Delays AS (SELECT origin_id, destination_id, flight_no, ROUND((julianday(actual_arr) - julianday(scheduled_arr))*1440, 2) AS delay_mins, ROW_NUMBER() OVER (PARTITION BY origin_id, destination_id ORDER BY (julianday(actual_arr) - julianday(scheduled_arr)) DESC) AS rn FROM flights WHERE actual_arr IS NOT NULL) SELECT origin_id, destination_id, flight_no, delay_mins FROM Delays WHERE rn = 1;"),
  make(237, 'airlines', 'hard', ['CTE', 'Aggregate', 'company:Microsoft', 'topic:CTEs'], "Compute the Revenue per Available Seat Kilometer (RASK) for each aircraft model. (Total Revenue / (Total Seats * Total Distance Flown)). Return model and rask.", "RASK = SUM(price) / SUM(seating_capacity * distance_km)", "Be careful about joins so you don't multiply incorrectly. CTEs help.", "WITH FlightStats AS (SELECT f.flight_id, a.model, a.seating_capacity, r.distance_km, COALESCE(SUM(b.price), 0) AS flight_rev FROM flights f JOIN aircraft a ON f.aircraft_id = a.aircraft_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id LEFT JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_id, a.model, a.seating_capacity, r.distance_km) SELECT model, ROUND(SUM(flight_rev) / SUM(seating_capacity * distance_km), 4) AS rask FROM FlightStats GROUP BY model;", "WITH FlightStats AS (SELECT f.flight_id, a.model, a.seating_capacity, r.distance_km, COALESCE(SUM(b.price), 0) AS flight_rev FROM flights f JOIN aircraft a ON f.aircraft_id = a.aircraft_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id LEFT JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_id, a.model, a.seating_capacity, r.distance_km) SELECT model, ROUND(SUM(flight_rev) / SUM(seating_capacity * distance_km), 4) AS rask FROM FlightStats GROUP BY model;"),
  make(238, 'airlines', 'hard', ['Window Function', 'company:Amazon', 'topic:Window Functions'], "Identify the top 3 employees who have worked on flights that generated the most revenue. Return employee name (first+last), role, and total_revenue_assisted.", "Calculate total revenue per flight, then join to crew and employee, aggregate, order and limit.", "This doesn't strictly need a window function, but DENSE_RANK can handle ties.", "SELECT e.first_name || ' ' || e.last_name AS employee_name, c.role, SUM(b.price) AS total_revenue_assisted FROM employees e JOIN crew c ON e.employee_id = c.employee_id JOIN flights f ON c.flight_id = f.flight_id JOIN bookings b ON f.flight_id = b.flight_id GROUP BY e.employee_id, c.role ORDER BY total_revenue_assisted DESC LIMIT 3;", "SELECT e.first_name || ' ' || e.last_name AS employee_name, c.role, SUM(b.price) AS total_revenue_assisted FROM employees e JOIN crew c ON e.employee_id = c.employee_id JOIN flights f ON c.flight_id = f.flight_id JOIN bookings b ON f.flight_id = b.flight_id GROUP BY e.employee_id, c.role ORDER BY total_revenue_assisted DESC LIMIT 3;"),
  make(239, 'airlines', 'hard', ['Window Function', 'Lead/Lag', 'company:Salesforce', 'topic:Window Functions'], "Find passengers whose booking price is strictly increasing across their chronological bookings (must have at least 3 bookings). Return passenger_id.", "Compare current price to previous price using LAG", "Count bookings, and count where price > prev_price. If equal, they are strictly increasing.", "WITH OrderedBookings AS (SELECT passenger_id, price, LAG(price) OVER (PARTITION BY passenger_id ORDER BY booked_at) AS prev_price FROM bookings), PriceTrends AS (SELECT passenger_id, COUNT(*) AS total_bookings, SUM(CASE WHEN prev_price IS NULL OR price > prev_price THEN 1 ELSE 0 END) AS increasing_steps FROM OrderedBookings GROUP BY passenger_id) SELECT passenger_id FROM PriceTrends WHERE total_bookings >= 3 AND total_bookings = increasing_steps;", "WITH OrderedBookings AS (SELECT passenger_id, price, LAG(price) OVER (PARTITION BY passenger_id ORDER BY booked_at) AS prev_price FROM bookings), PriceTrends AS (SELECT passenger_id, COUNT(*) AS total_bookings, SUM(CASE WHEN prev_price IS NULL OR price > prev_price THEN 1 ELSE 0 END) AS increasing_steps FROM OrderedBookings GROUP BY passenger_id) SELECT passenger_id FROM PriceTrends WHERE total_bookings >= 3 AND total_bookings = increasing_steps;"),
  make(240, 'airlines', 'hard', ['CTE', 'Join', 'company:Uber', 'topic:CTEs'], "Create a 'Flight Scorecard': for each flight, calculate Load Factor (%), Yield (Revenue/(Pax*Distance)), and Delay (mins). Return flight_no, load_factor, yield, and delay_mins for the top 5 flights by Yield.", "Combine metrics using CTEs", "Yield = SUM(price) / (COUNT(pax) * distance)", "WITH Metrics AS (SELECT f.flight_no, ROUND(COUNT(b.booking_id)*100.0/a.seating_capacity, 2) AS load_factor, ROUND(SUM(b.price)/(COUNT(b.booking_id)*r.distance_km), 4) AS yield, ROUND((julianday(f.actual_arr)-julianday(f.scheduled_arr))*1440, 2) AS delay_mins FROM flights f JOIN aircraft a ON f.aircraft_id = a.aircraft_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id LEFT JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_id) SELECT flight_no, load_factor, yield, delay_mins FROM Metrics WHERE yield IS NOT NULL ORDER BY yield DESC LIMIT 5;", "WITH Metrics AS (SELECT f.flight_no, ROUND(COUNT(b.booking_id)*100.0/a.seating_capacity, 2) AS load_factor, ROUND(SUM(b.price)/(COUNT(b.booking_id)*r.distance_km), 4) AS yield, ROUND((julianday(f.actual_arr)-julianday(f.scheduled_arr))*1440, 2) AS delay_mins FROM flights f JOIN aircraft a ON f.aircraft_id = a.aircraft_id JOIN routes r ON f.origin_id = r.origin_id AND f.destination_id = r.destination_id LEFT JOIN bookings b ON f.flight_id = b.flight_id GROUP BY f.flight_id) SELECT flight_no, load_factor, yield, delay_mins FROM Metrics WHERE yield IS NOT NULL ORDER BY yield DESC LIMIT 5;")
];
`;

fs.writeFileSync(targetFile, code);
console.log('Successfully updated airlines questions!');
